name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  aevoria-front:
    name: Aevoria Front - Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Étapes de lint - le pipeline échoue si erreurs détectées
      - name: Lint JavaScript/React
        run: npm run lint

      - name: Lint SCSS
        run: npm run lint:scss

      - name: Lint All (Combined check)
        run: npm run lint:all

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aevoria-front-build
          path: dist/
          retention-days: 7



  # Job optionnel pour les tests si tu en ajoutes plus tard
  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   needs: [aevoria-front, aevoria-panel]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18
  #         cache: 'npm'
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run tests
  #       run: npm test

